### ISSUE TITLE
!md <args> seems to not work in direct messages

### ISSUE THREAD

**Issue by TorleifHensvold** [Mendenj85/Bitburner-Scripts-by-Deaeth85#25] opened 2022-01-24 18:10 UTC
I've tried with !md hack, !md ns.hack, !md ftpcrack, !md exec, !md exit. And also just !md to try to get the special usage message.
Something about the update seems to have broken direct message !md

!help still works, though, as well as the other commands seems to work.

**Comment by TorleifHensvold** [comment] 2022-01-24 18:11
This is specifically in relation to the Bitburner Help Bot

**Comment by Mendenj85** [comment] 2022-01-24 21:07
Try again and let me know if you are getting the same issues.

**Comment by FrostyFire1** [comment] 2022-01-25 10:12
This is caused by !md checking a channel's name attribute which doesn't exist in DMs. Working on a fix

**Comment by TorleifHensvold** [comment] 2022-01-25 12:35
Thanks for looking into it, I just figured I should report it as an issue

**Comment by FrostyFire1** [comment] 2022-01-25 12:59
Issue fixed in #26

**Closed as completed by FrostyFire1** 2022-01-25 12:59 UTC
Labels: bug
